/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"github.com/gorilla/mux"
	"log"
	"net/http"
)

type UserApi interface {
	CreateUser(body User) (int, map[string]string, interface{})
	CreateUsersWithArrayInput(body []User) (int, map[string]string, interface{})
	CreateUsersWithListInput(body []User) (int, map[string]string, interface{})
	DeleteUser(username string) (int, map[string]string, interface{})
	GetUserByName(username string) (int, map[string]string, interface{})
	LoginUser(username string, password string) (int, map[string]string, interface{})
	LogoutUser() (int, map[string]string, interface{})
	UpdateUser(body User, username string) (int, map[string]string, interface{})
}

func CreateUserHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var body User

		bodyErr := json.NewDecoder(r.Body).Decode(&body)
		if bodyErr != nil {
			http.Error(w, bodyErr.Error(), http.StatusBadRequest)
			return
		}
		statusCode, headers, response := p.CreateUser(body)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func CreateUsersWithArrayInputHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var body []User

		bodyErr := json.NewDecoder(r.Body).Decode(&body)
		if bodyErr != nil {
			http.Error(w, bodyErr.Error(), http.StatusBadRequest)
			return
		}
		statusCode, headers, response := p.CreateUsersWithArrayInput(body)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func CreateUsersWithListInputHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var body []User

		bodyErr := json.NewDecoder(r.Body).Decode(&body)
		if bodyErr != nil {
			http.Error(w, bodyErr.Error(), http.StatusBadRequest)
			return
		}
		statusCode, headers, response := p.CreateUsersWithListInput(body)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func DeleteUserHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var username string

		pathParams := mux.Vars(r)
		username = pathParams["username"]
		statusCode, headers, response := p.DeleteUser(username)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func GetUserByNameHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var username string

		pathParams := mux.Vars(r)
		username = pathParams["username"]
		statusCode, headers, response := p.GetUserByName(username)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func LoginUserHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var username string
		var password string

		params := r.URL.Query()
		username = params.Get("username")
		password = params.Get("password")
		statusCode, headers, response := p.LoginUser(username, password)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func LogoutUserHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error

		statusCode, headers, response := p.LogoutUser()
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
func UpdateUserHandler(p UserApi) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var b []byte
		var err error
		var body User
		var username string

		pathParams := mux.Vars(r)
		username = pathParams["username"]
		bodyErr := json.NewDecoder(r.Body).Decode(&body)
		if bodyErr != nil {
			http.Error(w, bodyErr.Error(), http.StatusBadRequest)
			return
		}
		statusCode, headers, response := p.UpdateUser(body, username)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		for key, value := range headers {
			w.Header().Set(key, value)
		}
		if b, err = json.Marshal(response); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		if _, err = w.Write(b); err != nil {

			log.Printf(err.Error())
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		w.WriteHeader(statusCode)
	}
}
