/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import ()

type ImpStoreApi struct {
}

func (t ImpStoreApi) DeleteOrder(orderId int64) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpStoreApi) GetInventory() (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpStoreApi) GetOrderById(orderId int64) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpStoreApi) PlaceOrder(body Order) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
