/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"os"
)

type ImpPetApi struct {
}

func (t ImpPetApi) AddPet(body Pet) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) DeletePet(petId int64, apiKey string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) FindPetsByStatus(status []string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) FindPetsByTags(tags []string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) GetPetById(petId int64) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) UpdatePet(body Pet) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) UpdatePetWithForm(petId int64, name string, status string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpPetApi) UploadFile(petId int64, additionalMetadata string, file *os.File) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
