/*
 * Swagger Petstore
 *
 * This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import ()

type ImpUserApi struct {
}

func (t ImpUserApi) CreateUser(body User) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) CreateUsersWithArrayInput(body []User) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) CreateUsersWithListInput(body []User) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) DeleteUser(username string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) GetUserByName(username string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) LoginUser(username string, password string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) LogoutUser() (int, map[string]string, interface{}) {
	return 501, nil, nil
}
func (t ImpUserApi) UpdateUser(body User, username string) (int, map[string]string, interface{}) {
	return 501, nil, nil
}
